### PR TITLE
hybrid payment fix, admin translations

### PR DESCRIPTION
**Pull request by mareknaujas**

### CODE REVIEW

**Review by saltanovas — CHANGES_REQUESTED** [review]
@mareknaujas the written code does not comply with our defined code style. Please do the appropriate changes.

**Review by tomas-maciulis — CHANGES_REQUESTED** [review]
Style errors are still present, you can see the error log by clicking on style checker task details.
image

**Comment by mareknaujas** [comment]
> Style errors are still present, you can see the error log by clicking on style checker task details. image

Irasiau pas save PHP CS FIXER, paleidau komanda "PHP_CS_Fixer/vendor/bin/php-cs-fixer fix Model/Adapter.php", idejau i git bet vis tiek kazkas nepatinka. Kodel netinka nzn

**Comment by tomas-maciulis** [comment]
> > Style errors are still present, you can see the error log by clicking on style checker task details. image
> 
> Irasiau pas save PHP CS FIXER, paleidau komanda "PHP_CS_Fixer/vendor/bin/php-cs-fixer fix Model/Adapter.php", idejau i git bet vis tiek kazkas nepatinka. Kodel netinka nzn

Galimai neperduodama mūsų konfigūracija, rekomenduoju naudot `composer fix-style` komandą arba tiesiog pataisyt rankiniu būdu kadangi ten poros kabelių tik trūksta.

**Comment by mareknaujas** [comment]
> 

sutvarkyta

**Review by tomas-maciulis — APPROVED** [review]

**Review by saltanovas — APPROVED** [review]

**Pull request merged**
